[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["database.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
